### ISSUE TITLE
Android client doesn't sync

### ISSUE THREAD

**Issue by M1n-4d316e** [Liso-Vault/app#5] opened 2022-10-08 09:36 UTC
The Android client does not sync with the cloud. Following Discord's talk, the problem is not only that you can't sync a newly created vault, but also that you can't restore a vault from Windows to Android.

**Comment by M1n-4d316e** [comment] 2022-10-08 10:11
I think the loader you were referring to was this, It never appears on Android. 🤔
I will check it later on other devices.

![NexSnap-Oct-08-2022_12-05-48_PM](https://user-images.githubusercontent.com/54779580/194702189-62cded57-aa24-4cc9-8ecf-5e47fa19ac8d.png)

**Comment by oliverbytes** [comment] 2022-10-21 07:17
This is now fixed in the next version! It's caused by an uninitialized Remote Config from Firebase. Thank you very much!

**Closed by oliverbytes** 2022-10-21 07:17 UTC
